"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Student_1 = require("./src/Student");
var StudentManager_1 = require("./src/StudentManager");
var student1 = new Student_1.default("Manh", "C10M", 5);
var student2 = new Student_1.default("Dung", "C10M", 8);
var student3 = new Student_1.default("Quan", "C10M", 9);
var student4 = new Student_1.default("Mai", "C10M", 4);
var student5 = new Student_1.default("Bao", "C10M", 2);
var studentManager = new StudentManager_1.default();
studentManager.add(student1);
studentManager.add(student2);
studentManager.add(student3);
studentManager.add(student4);
studentManager.add(student5);
studentManager.showList();
console.log("---Student failed: " + studentManager.totalStudentsFail());
console.log("---Find student by name: Manh");
console.table(studentManager.findStudentByName("Manh2"));
